In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df=pd.read_csv("India_housing_prices.csv")

In [7]:
df.head()

,Property_ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,1,Delhi,Delhi,Locality_130,Apartment,4,2538,457.17,0.1801,1993,...,32,6,2,High,Yes,Yes,"Clubhouse, Playground, Gym",South,Broker,Under_Construction
1,2,Uttar Pradesh,Lucknow,Locality_245,Apartment,1,654,35.25,0.0539,2009,...,16,7,8,Low,Yes,Yes,"Playground, Pool, Garden, Clubhouse, Gym",East,Broker,Ready_to_Move
2,3,Rajasthan,Jodhpur,Locality_253,Apartment,1,947,44.88,0.0474,2002,...,23,9,2,Low,No,Yes,"Playground, Clubhouse, Gym, Pool",South,Builder,Ready_to_Move
3,4,West Bengal,Kolkata,Locality_241,Apartment,3,2072,174.43,0.0842,2014,...,11,5,0,Medium,Yes,No,"Playground, Gym",North,Builder,Ready_to_Move
4,5,West Bengal,Kolkata,Locality_12,Independent House,5,2331,197.42,0.0847,2010,...,15,6,9,Low,Yes,No,NaN,West,Owner,Ready_to_Move

In [9]:
df.sample(5)

,Property_ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
158211,158212,Telangana,Hyderabad,Locality_432,Apartment,5,2921,304.78,0.1043,2002,...,23,3,1,High,Yes,No,"Gym, Playground",East,Broker,Ready_to_Move
85504,85505,Punjab,Ludhiana,Locality_64,Apartment,5,3057,154.06,0.0504,2010,...,15,3,6,Low,Yes,Yes,"Clubhouse, Pool, Playground, Gym",South,Owner,Ready_to_Move
42810,42811,Tamil Nadu,Chennai,Locality_290,Independent House,3,2215,253.40,0.1144,2024,...,1,4,7,High,Yes,Yes,"Playground, Garden, Gym, Pool",East,Broker,Under_Construction
227599,227600,Kerala,Kochi,Locality_265,Apartment,1,1031,83.43,0.0809,2003,...,22,6,10,High,Yes,Yes,"Garden, Gym, Clubhouse",West,Builder,Ready_to_Move
85391,85392,West Bengal,Kolkata,Locality_123,Apartment,4,2708,205.25,0.0758,1999,...,26,1,10,Medium,Yes,Yes,"Clubhouse, Playground, Pool, Gym",East,Broker,Under_Construction

In [11]:
df.columns

Index(['Property_ID', 'State', 'City', 'Locality', 'Property_Type', 'BHK',
       'Size_in_SqFt', 'Price_in_Lakhs', 'Price_per_SqFt', 'Year_Built',
       'Furnished_Status', 'Floor_No', 'Total_Floors', 'Age_of_Property',
       'Nearby_Schools', 'Nearby_Hospitals', 'Public_Transport_Accessibility',
       'Parking_Space', 'Security', 'Amenities', 'Facing', 'Owner_Type',
       'Availability_Status'],
      dtype='object')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 23 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Property_ID                     250000 non-null  int64
 1   State                           250000 non-null  object
 2   City                            250000 non-null  object
 3   Locality                        250000 non-null  object
 4   Property_Type                   250000 non-null  object
 5   BHK                             250000 non-null  int64
 6   Size_in_SqFt                    250000 non-null  int64
 7   Price_in_Lakhs                  250000 non-null  float64
 8   Price_per_SqFt                  250000 non-null  float64
 9   Year_Built                      250000 non-null  int64
 10  Furnished_Status                250000 non-null  object
 11  Floor_No                        250000 non-null  int64
 12  Total_Floors                    250000 non-null  int64
 13  Age_of_Property                 250000 non-null  int64
 14  Nearby_Schools                  250000 non-null  int64
 15  Nearby_Hospitals                250000 non-null  int64
 16  Public_Transport_Accessibility  250000 non-null  object
 17  Parking_Space                   250000 non-null  object
 18  Security                        250000 non-null  object
 19  Amenities                       208246 non-null  object
 20  Facing                          250000 non-null  object
 21  Owner_Type                      250000 non-null  object
 22  Availability_Status             250000 non-null  object
dtypes: float64(2), int64(9), object(12)
memory usage: 43.9+ MB

The `Amenities` column contains 'nan' values that need to be filled with 'None', as some properties do not have any amenities.

In [13]:
df.State.unique()

array(['Delhi', 'Uttar Pradesh', 'Rajasthan', 'West Bengal', 'Punjab',
       'Maharashtra', 'Gujarat', 'Madhya Pradesh', 'Tamil Nadu',
       'Karnataka', 'Kerala', 'Telangana'], dtype=object)

In [15]:
df.City.unique()

array(['Delhi', 'Lucknow', 'Jodhpur', 'Kolkata', 'Chandigarh', 'Ludhiana',
       'Pune', 'Ahmedabad', 'Indore', 'Chennai', 'Bengaluru', 'Kochi',
       'Jaipur', 'Mumbai', 'Hyderabad'], dtype=object)

city always belongs to exactly the same state

In [19]:
df.Locality.unique() # high cardinality in this columns ->remove it

array(['Locality_130', 'Locality_245', 'Locality_253', 'Locality_241',
       'Locality_12', 'Locality_408', 'Locality_64', 'Locality_49',
       'Locality_471', 'Locality_214', 'Locality_482', 'Locality_76',
       'Locality_421', 'Locality_339', 'Locality_350', 'Locality_104',
       'Locality_364', 'Locality_140', 'Locality_156', 'Locality_473',
       'Locality_347', 'Locality_344', 'Locality_150', 'Locality_469',
       'Locality_430', 'Locality_497', 'Locality_462', 'Locality_481',
       'Locality_311', 'Locality_255', 'Locality_479', 'Locality_70',
       'Locality_424', 'Locality_475', 'Locality_483', 'Locality_199',
       'Locality_41', 'Locality_60', 'Locality_286', 'Locality_368',
       'Locality_232', 'Locality_273', 'Locality_211', 'Locality_215',
       'Locality_301', 'Locality_201', 'Locality_111', 'Locality_162',
       'Locality_319', 'Locality_412', 'Locality_20', 'Locality_284',
       'Locality_449', 'Locality_393', 'Locality_467', 'Locality_288',
       'Locality_499', 'Locality_252', 'Locality_171', 'Locality_141',
       'Locality_97', 'Locality_37', 'Locality_267', 'Locality_138',
       'Locality_6', 'Locality_307', 'Locality_323', 'Locality_434',
       'Locality_468', 'Locality_303', 'Locality_169', 'Locality_32',
       'Locality_88', 'Locality_324', 'Locality_126', 'Locality_474',
       'Locality_57', 'Locality_204', 'Locality_229', 'Locality_407',
       'Locality_308', 'Locality_133', 'Locality_187', 'Locality_16',
       'Locality_282', 'Locality_389', 'Locality_83', 'Locality_491',
       'Locality_341', 'Locality_96', 'Locality_431', 'Locality_220',
       'Locality_72', 'Locality_142', 'Locality_244', 'Locality_119',
       'Locality_58', 'Locality_420', 'Locality_387', 'Locality_249',
       'Locality_441', 'Locality_165', 'Locality_346', 'Locality_228',
       'Locality_309', 'Locality_314', 'Locality_79', 'Locality_342',
       'Locality_101', 'Locality_298', 'Locality_75', 'Locality_269',
       'Locality_99', 'Locality_454', 'Locality_374', 'Locality_318',
       'Locality_401', 'Locality_51', 'Locality_305', 'Locality_151',
       'Locality_294', 'Locality_170', 'Locality_463', 'Locality_348',
       'Locality_87', 'Locality_248', 'Locality_27', 'Locality_139',
       'Locality_445', 'Locality_439', 'Locality_56', 'Locality_331',
       'Locality_183', 'Locality_356', 'Locality_181', 'Locality_432',
       'Locality_21', 'Locality_221', 'Locality_191', 'Locality_264',
       'Locality_492', 'Locality_102', 'Locality_82', 'Locality_325',
       'Locality_251', 'Locality_5', 'Locality_84', 'Locality_61',
       'Locality_487', 'Locality_190', 'Locality_148', 'Locality_105',
       'Locality_290', 'Locality_193', 'Locality_203', 'Locality_395',
       'Locality_98', 'Locality_362', 'Locality_260', 'Locality_202',
       'Locality_367', 'Locality_477', 'Locality_450', 'Locality_403',
       'Locality_280', 'Locality_29', 'Locality_154', 'Locality_287',
       'Locality_312', 'Locality_366', 'Locality_466', 'Locality_381',
       'Locality_164', 'Locality_283', 'Locality_146', 'Locality_352',
       'Locality_224', 'Locality_93', 'Locality_223', 'Locality_410',
       'Locality_272', 'Locality_136', 'Locality_44', 'Locality_460',
       'Locality_33', 'Locality_4', 'Locality_436', 'Locality_370',
       'Locality_194', 'Locality_472', 'Locality_127', 'Locality_398',
       'Locality_239', 'Locality_22', 'Locality_330', 'Locality_429',
       'Locality_242', 'Locality_486', 'Locality_419', 'Locality_258',
       'Locality_394', 'Locality_176', 'Locality_480', 'Locality_120',
       'Locality_222', 'Locality_237', 'Locality_397', 'Locality_493',
       'Locality_157', 'Locality_236', 'Locality_137', 'Locality_106',
       'Locality_326', 'Locality_390', 'Locality_447', 'Locality_184',
       'Locality_186', 'Locality_406', 'Locality_338', 'Locality_415',
       'Locality_275', 'Locality_277', 'Locality_327', 'Locality_405',
       'Locality_299', 'Locality_351', 'Locality_145', 'Locality_108',
       'Locality_265', 'Locality_235', 'Locality_377', 'Locality_65',
       'Locality_250', 'Locality_375', 'Locality_254', 'Locality_14',
       'Locality_278', 'Locality_322', 'Locality_465', 'Locality_409',
       'Locality_302', 'Locality_26', 'Locality_452', 'Locality_217',
       'Locality_110', 'Locality_89', 'Locality_179', 'Locality_478',
       'Locality_185', 'Locality_276', 'Locality_132', 'Locality_69',
       'Locality_243', 'Locality_200', 'Locality_95', 'Locality_189',
       'Locality_285', 'Locality_461', 'Locality_334', 'Locality_46',
       'Locality_67', 'Locality_125', 'Locality_427', 'Locality_9',
       'Locality_43', 'Locality_498', 'Locality_423', 'Locality_262',
       'Locality_208', 'Locality_310', 'Locality_349', 'Locality_94',
       'Locality_257', 'Locality_231', 'Locality_357', 'Locality_212',
       'Locality_464', 'Locality_68', 'Locality_159', 'Locality_315',
       'Locality_418', 'Locality_422', 'Locality_428', 'Locality_380',
       'Locality_292', 'Locality_15', 'Locality_335', 'Locality_48',
       'Locality_313', 'Locality_178', 'Locality_59', 'Locality_438',
       'Locality_489', 'Locality_456', 'Locality_36', 'Locality_317',
       'Locality_413', 'Locality_384', 'Locality_379', 'Locality_167',
       'Locality_52', 'Locality_291', 'Locality_24', 'Locality_118',
       'Locality_175', 'Locality_90', 'Locality_100', 'Locality_455',
       'Locality_109', 'Locality_383', 'Locality_124', 'Locality_488',
       'Locality_7', 'Locality_107', 'Locality_53', 'Locality_92',
       'Locality_10', 'Locality_296', 'Locality_1', 'Locality_218',
       'Locality_360', 'Locality_74', 'Locality_42', 'Locality_30',
       'Locality_361', 'Locality_123', 'Locality_35', 'Locality_476',
       'Locality_343', 'Locality_496', 'Locality_238', 'Locality_131',
       'Locality_226', 'Locality_293', 'Locality_247', 'Locality_227',
       'Locality_337', 'Locality_129', 'Locality_444', 'Locality_116',
       'Locality_459', 'Locality_442', 'Locality_404', 'Locality_281',
       'Locality_153', 'Locality_332', 'Locality_316', 'Locality_402',
       'Locality_391', 'Locality_168', 'Locality_328', 'Locality_173',
       'Locality_174', 'Locality_8', 'Locality_261', 'Locality_378',
       'Locality_470', 'Locality_321', 'Locality_128', 'Locality_34',
       'Locality_50', 'Locality_77', 'Locality_147', 'Locality_54',
       'Locality_373', 'Locality_336', 'Locality_233', 'Locality_197',
       'Locality_433', 'Locality_485', 'Locality_3', 'Locality_55',
       'Locality_216', 'Locality_66', 'Locality_333', 'Locality_435',
       'Locality_458', 'Locality_443', 'Locality_219', 'Locality_209',
       'Locality_354', 'Locality_494', 'Locality_451', 'Locality_446',
       'Locality_263', 'Locality_490', 'Locality_188', 'Locality_122',
       'Locality_297', 'Locality_144', 'Locality_279', 'Locality_115',
       'Locality_114', 'Locality_270', 'Locality_143', 'Locality_86',
       'Locality_18', 'Locality_177', 'Locality_295', 'Locality_358',
       'Locality_369', 'Locality_396', 'Locality_39', 'Locality_152',
       'Locality_121', 'Locality_271', 'Locality_448', 'Locality_213',
       'Locality_359', 'Locality_457', 'Locality_329', 'Locality_163',
       'Locality_266', 'Locality_300', 'Locality_320', 'Locality_180',
       'Locality_411', 'Locality_62', 'Locality_195', 'Locality_198',
       'Locality_63', 'Locality_81', 'Locality_256', 'Locality_363',
       'Locality_306', 'Locality_31', 'Locality_289', 'Locality_172',
       'Locality_386', 'Locality_91', 'Locality_376', 'Locality_246',
       'Locality_135', 'Locality_225', 'Locality_117', 'Locality_38',
       'Locality_210', 'Locality_113', 'Locality_495', 'Locality_23',
       'Locality_400', 'Locality_206', 'Locality_268', 'Locality_182',
       'Locality_103', 'Locality_304', 'Locality_425', 'Locality_149',
       'Locality_73', 'Locality_382', 'Locality_437', 'Locality_372',
       'Locality_2', 'Locality_45', 'Locality_17', 'Locality_345',
       'Locality_440', 'Locality_353', 'Locality_71', 'Locality_484',
       'Locality_28', 'Locality_416', 'Locality_340', 'Locality_155',
       'Locality_80', 'Locality_13', 'Locality_207', 'Locality_192',
       'Locality_388', 'Locality_259', 'Locality_25', 'Locality_11',
       'Locality_78', 'Locality_205', 'Locality_19', 'Locality_40',
       'Locality_365', 'Locality_230', 'Locality_196', 'Locality_355',
       'Locality_371', 'Locality_453', 'Locality_47', 'Locality_414',
       'Locality_166', 'Locality_134', 'Locality_85', 'Locality_161',
       'Locality_234', 'Locality_392', 'Locality_426', 'Locality_158',
       'Locality_240', 'Locality_274', 'Locality_160', 'Locality_112',
       'Locality_399', 'Locality_385', 'Locality_417'], dtype=object)

In [24]:
df.Property_Type.unique()

array(['Apartment', 'Independent House', 'Villa'], dtype=object)

In [28]:
df.BHK.unique() # max bhk

array([4, 1, 3, 5, 2], dtype=int64)